### DISCUSSION TITLE
Unraid/DockerHub

### DISCUSSION THREAD

**Discussion by charlie-kilo13** [Peppermint-Lab/peppermint#226] [Ideas]
Would love to run this on my Unraid Server.  This would be fantastic!  Needs to be added to community apps or via dockerhub...

**Comment by thackmaster** [comment]
Not familiar with Unraid so I don't know if this will solve your comment, but I've been pulling Docker Hub for a while now. [https://hub.docker.com/r/pepperlabs/peppermint](https://hub.docker.com/r/pepperlabs/peppermint)

**Comment by SolidProgramming** [comment]
> Would love to run this on my Unraid Server. This would be fantastic! Needs to be added to community apps or via dockerhub...

I know this discussion is old but i stumbled upon this because i wanted to have this for my unraid server too! I made it work with the "compose manager" plugin and following compose file:

(Adjust mounts, ips and passwords as you need)
````YML
services:
  peppermint_postgres:
    container_name: peppermint_postgres
    image: postgres:latest
    restart: always
    volumes:
      - /mnt/user/appdata/peppermint_postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: peppermint
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: peppermint
    networks:
      - br0
 
  peppermint:
    container_name: peppermint
    image: pepperlabs/peppermint:latest
    ports:
      - 3000:3000
      - 5003:5003
    restart: always
    depends_on:
      - peppermint_postgres
    environment:
      DB_USERNAME: "peppermint"
      DB_PASSWORD: "1234"
      DB_HOST: "peppermint_postgres"
      SECRET: 'peppermint4life'
    networks:
      br0:
        ipv4_address: 192.168.1.5
      
networks:
  br0:
    name: br0
    external: true
````
![brave_silv2EmlnI](https://github.com/user-attachments/assets/4bd0abdc-7bb1-4f34-a750-074a53ed820a)
