### ISSUE TITLE
Error when reverse proxy is using a certificate not in CA trust

### ISSUE THREAD

**Issue by tperrindell** [Peppermint-Lab/peppermint#116]
Hello !

I'm trying to setup peppermint to take a look at what I could be using it for.

I'm using traefik. Here is my docker-compose with some things redacted:
```
version: "3.1"

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    networks:
      - peppermint
    volumes:
      - ./db:/data/db
    environment:
      POSTGRES_USER: peppermint
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: peppermint

  client:
    container_name: peppermint
    image: pepperlabs/peppermint:latest
    restart: on-failure
    networks:
      - peppermint
      - traefik
    depends_on:
      - postgres
    environment:
      PORT: 5000
      DB_USERNAME: peppermint
      DB_PASSWORD: 1234
      DB_HOST: 'postgres'
      BASE_URL: "https://bugs.domain.com"
      HTTPS_PROXY: "http://xxxx"
      HTTP_PROXY: "http://xxxx"
      NO_PROXY: "internal.local"

    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.peppermint.rule=Host(`bugs.domain.com`)"
      - "traefik.http.routers.peppermint.entrypoints=web,websecure"
      - "traefik.http.services.peppermint.loadbalancer.server.port=5000"
      - "traefik.http.routers.peppermint.tls=true"

networks:
  peppermint:
  traefik:
    external: true
```

When I start the container, it gathers the db stuff, runs the migration scripts, and the landing page appears.

But when I try to login, it falls back to the login page, and this error appears:
```
  header: {
    host: 'bugs.domain.com',
    'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36',
    accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9',
    'accept-encoding': 'gzip, deflate, br',
    'accept-language': 'en-US,en;q=0.9',
    'cache-control': 'max-age=0',
    cookie: 'XSRF-TOKEN=eyJpdiI6IndMSENDbkNFTzZNaUZ4WmRManp5eXc9PSIsInZhbHVlIjoiTGNsUnVhWUI4eGJ5RkxnZFdrOSt6d250bnlkb0ZjRlp5dVwvbkl3TXZaRWdMblo5UENZeVkxZ1NSUjBDMThiVlpqMWVvRklpVHRHTEcyUkhqNTNlK1RBPT0iLCJtYWMiOiJkMjI5ODhmM2FkNjJmMDNiMzEwMDkxNGM0OTkyODg4MzQwNGQ1M2ExNTlkMTc0NGUxMzg1NzQ1ZDc1NjI1NjAwIn0%3D; laravel_session=eyJpdiI6IjdtSTNhRzIzU2RoMVFRd2w3RDZkY0E9PSIsInZhbHVlIjoiOTBOOVZvUWV2bFluN25nUzFaOWlZN0F5eDhqTzNkNTlhanVTeWE2bDZrbzVxQnRhQkk0bHl5eVpxRjUzbmdQZXcwTjFKeituMVJsZ1JOMEJQc1pOTGc9PSIsIm1hYyI6IjkyYTk5ZTRmYWM2ZjJmM2RhMGQxYmYwZDE3Nzg1NzM4ZTQyNzczNWYwNzhlOWFiODc4MjVjNDFhZDRkODA4Y2QifQ%3D%3D; next-auth.csrf-token=4e2f7dd7a7113c1d4819000c275eb32bcdb11e0802cc9481406581930ba09b2d%7Cf5b7dac5475b0956f6dd250f954f4cbbc6ad9caef924038374fd1d2535dfa46d; next-auth.callback-url=http%3A%2F%2Flocalhost; __Host-next-auth.csrf-token=31dd18883a97e0fd9842392a3cc7c62c8ec242e65768c0543794206165fcd7f7%7Cd0c04e54fc09561ea9adc9276233a8421764ffecf54d9c92d09b26b66503593b; __Secure-next-auth.callback-url=https%3A%2F%2Fbugs.domain.com%2Fapp-settings%2Falerts',
    referer: 'https://bugs.domain.com/auth/login?callbackUrl=https://bugs.domain.com/app-settings/alerts',
    'sec-ch-ua': '"Not?A_Brand";v="8", "Chromium";v="108", "Google Chrome";v="108"',
    'sec-ch-ua-mobile': '?0',
    'sec-ch-ua-platform': '"Windows"',
    'sec-fetch-dest': 'document',
    'sec-fetch-mode': 'navigate',
    'sec-fetch-site': 'same-origin',
    'sec-fetch-user': '?1',
    'upgrade-insecure-requests': '1',
    'x-forwarded-for': '10.x.x.x',
    'x-forwarded-host': 'bugs.domain.com',
    'x-forwarded-port': '443',
    'x-forwarded-proto': 'https',
    'x-forwarded-server': '415ed55a6ee5',
    'x-real-ip': '10.x.x.x'
  },
  message: 'request to https://bugs.domain.com/api/auth/csrf failed, reason: unable to verify the first certificate'
}
undefined
```

My certificate for domain.com is an internal certificate authority.

Do I have to create an image from peppermint to add my certs & run an update-ca-trust or is there a way for peppermint to ignore that ?

Thanks,
