### ISSUE TITLE
Issues behind reverse proxy. 

### ISSUE THREAD

**Issue by WoodardDigital** [Peppermint-Lab/peppermint#123]
Hello... 

I think this is going to  be something that is  stupidly easy but I can't figure it out. This is  my first time posting an issue or question like this on Git, sorry if I am doing it in poor form. 

When I attempt to access the site it sits with the loading animation, I never get to the login page to setup the actual application. 

I have Peppermint behind Nginx Proxy Manager running on Docker. This is my Docker Compose
``` 
version: "3.1"

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    volumes:
      - ./docker-data/db:/data/db
    environment: 
      POSTGRES_USER: peppermint
      POSTGRES_PASSWORD: $password
      POSTGRES_DB: peppermint-postgres

  client:
    container_name: peppermint
    hostname: peppermint
    image: pepperlabs/peppermint:latest
    ports:
      - 5001:5001
    restart: on-failure
    depends_on:
      - postgres
    environment:
      PORT: 5001
      DB_USERNAME: peppermint
      DB_PASSWORD: $password
      DB_HOST: 'peppermint-postgres'
      BASE_URL: https://$my.$domain.$tld
``` 

My NPM configuration is as follows.

$Peppermint.$MYdomain.$TLD
Scheme = http 
Forward hostname = peppermint (I set hostnames for all containers in my docker networks)
Forward port = 5001

Cache Assets, Websockets support is on. 

SSL is a cert that is loaded in exactly the same way as all my other sites. 

The page just sits trying to load but finally times out. This is what I am watching from the container logs. 

``` 
message: 'request to $DOMAIN failed, reason: connect ETIMEDOUT $SERVER-IP:80',
    stack: 'FetchError: request to $Peppermint.$DOMAIN/api/auth/csrf failed, reason: connect ETIMEDOUT $SERVER-IP:80\n' +
      '    at ClientRequest.<anonymous> (/app/node_modules/node-fetch/lib/index.js:1461:11)\n' +
      '    at ClientRequest.emit (events.js:400:28)\n' +
      '    at Socket.socketErrorListener (_http_client.js:475:9)\n' +
      '    at Socket.emit (events.js:400:28)\n' +
      '    at emitErrorNT (internal/streams/destroy.js:106:8)\n' +
      '    at emitErrorCloseNT (internal/streams/destroy.js:74:3)\n' +
      '    at processTicksAndRejections (internal/process/task_queues.js:82:21)',
    name: 'FetchError'
  },
  path: 'csrf',
  header: {
    host: '$Peppermint.$DOMAIN.tld',
    'x-forwarded-scheme': 'https',
    'x-forwarded-proto': 'https',
    'x-forwarded-for': '$MY_HOME_IP',
    'x-real-ip': '$MY_HOME_IP',
    'upgrade-insecure-requests': '1',
    dnt: '1',
    'user-agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36',
    accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7',
    'sec-fetch-site': 'same-origin',
    'sec-fetch-mode': 'navigate',
    'sec-fetch-dest': 'document',
    'sec-ch-ua': '"Chromium";v="110", "Not A(Brand";v="24", "Google Chrome";v="110"',
    'sec-ch-ua-mobile': '?0',
    'sec-ch-ua-platform': '"Linux"',
    referer: 'https://$DOMAIN/',
    'accept-encoding': 'gzip, deflate, br',
    'accept-language': 'en-US,en;q=0.9',
    cookie: 'next-auth.csrf-token=1ff4151045fe89500a3748db09c0825f36d17a7d26c263b62727c5deb9ded98c%7C3b9b65dbf601708de64512f0188d6ed9e56399795db76e6c6007a06f75025aad; __Host-next-auth.csrf-token=72248a03ac609416ac822f0282ca736f2b8fdcf5afb9603808b77fd5ddf97974%7C5d2fe119994b2f2348d520fd5392ada3ed776a21f11015762d2f49cf5539a09c; __Secure-next-auth.callback-url=https%3A%2F%2F$Peppermint.$DOMAIN%2F; next-auth.callback-url=http%3A%2F%2F$DOMAIN'
  },
  message: 'request to http://$Peppermint.$DOMAIN/api/auth/csrf failed, reason: connect ETIMEDOUT $SERVER-IP:80'
}
undefined
``` 

By changing the ENV configuration to 
``` 
 BASE_URL: "https://$my.$domain.$tld"
``` 
I can access the login page, but then the redirect after trying to log in doesn't work. I've tried setting the base URL with and without the "Https" or just "http" or just "$MY.$DOMAIN.$TLD."   I've also tried it with and without double quotes around that variable
