### ISSUE TITLE
auth failed, reason: connect ECONNREFUSED 127.0.0.1:80

### ISSUE THREAD

**Issue by Mara01010011** [Peppermint-Lab/peppermint#133]
I am new to docker and don't yet understand networking that well. I used the docker-compose.yml of peppermint: https://docs.peppermint.sh/ and tried it on two different machines: Ubuntu in a VM not local server and arch-based local pc. Both receive the same error which I think is due to some docker networking error. It appears after I go to localhost:5000 in a webbrowser:

```
peppermint  | [next-auth][error][CLIENT_FETCH_ERROR] 
peppermint  | https://next-auth.js.org/errors#client_fetch_error request to http://localhost/api/auth/csrf failed, reason: connect ECONNREFUSED 127.0.0.1:80 {
peppermint  |   error: {
peppermint  |     message: 'request to http://localhost/api/auth/csrf failed, reason: connect ECONNREFUSED 127.0.0.1:80',
peppermint  |     stack: 'FetchError: request to http://localhost/api/auth/csrf failed, reason: connect ECONNREFUSED 127.0.0.1:80\n' +
peppermint  |       '    at ClientRequest.<anonymous> (/app/node_modules/node-fetch/lib/index.js:1461:11)\n' +
peppermint  |       '    at ClientRequest.emit (events.js:400:28)\n' +
peppermint  |       '    at Socket.socketErrorListener (_http_client.js:475:9)\n' +
peppermint  |       '    at Socket.emit (events.js:400:28)\n' +
peppermint  |       '    at emitErrorNT (internal/streams/destroy.js:106:8)\n' +
peppermint  |       '    at emitErrorCloseNT (internal/streams/destroy.js:74:3)\n' +
peppermint  |       '    at processTicksAndRejections (internal/process/task_queues.js:82:21)',
peppermint  |     name: 'FetchError'
peppermint  |   },
peppermint  |   path: 'csrf',
peppermint  |   header: {
peppermint  |     host: 'localhost:5000',
peppermint  |     'user-agent': 'Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/112.0',
peppermint  |     accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8',
peppermint  |     'accept-language': 'en-US,en;q=0.5',
peppermint  |     'accept-encoding': 'gzip, deflate, br',
peppermint  |     referer: 'http://localhost:5000/',
peppermint  |     dnt: '1',
peppermint  |     connection: 'keep-alive',
peppermint  |     cookie: 'next-auth.csrf-token=ab2ff4c4b6f7ebfc015ef2b71b5152ce5322a389c94f63504ece9c345d7d610b%7C10f9ee75f91a38a9886e7a9cb1d47ef04b8a4ecc4ca33520116aeacc22cd6d7f; next-auth.callback-url=http%3A%2F%2Flocalhost%3A5000%2F',
peppermint  |     'upgrade-insecure-requests': '1',
peppermint  |     'sec-fetch-dest': 'document',
peppermint  |     'sec-fetch-mode': 'navigate',
peppermint  |     'sec-fetch-site': 'same-origin'
peppermint  |   },
peppermint  |   message: 'request to http://localhost/api/auth/csrf failed, reason: connect ECONNREFUSED 127.0.0.1:80'
peppermint  | }
peppermint  | undefined
```
While building, I also see this:
```
peppermint  | $ prisma migrate deploy
peppermint  | Environment variables loaded from .env
peppermint  | Prisma schema loaded from prisma/schema.prisma
peppermint  | Datasource "db": PostgreSQL database "peppermint", schema "public" at "postgres:5432"
postgres    | 2023-04-19 21:19:47.514 UTC [33] LOG:  could not receive data from client: Connection reset by peer
```

Which disappears, when I add
```
ports:
      - 80:80 
 ```
to postgres but doesn't change the error message of peppermint.
Do I need to open a port in my own firewall? But my VM doesn't even have any preinstalled.

**Comment by potts99** [comment]
Hi what BASE_URL are you using?

**Comment by Mara01010011** [comment]
I used the original file with "localhost" as BASE_URL.

```
version: "3.1"

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    volumes:
      - ./docker-data/db:/data/db
    environment: 
      POSTGRES_USER: peppermint
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: peppermint

  client:
    container_name: peppermint
    image: pepperlabs/peppermint:latest
    ports:
      - 5000:5000
    restart: on-failure
    depends_on:
      - postgres
    environment:
      PORT: 5000
      DB_USERNAME: peppermint
      DB_PASSWORD: 1234
      DB_HOST: 'postgres'
      BASE_URL: "http://localhost"

```
