### ISSUE TITLE
Bug: Can't change admin email or make new user

### ISSUE THREAD

**Issue by jamess60** [Peppermint-Lab/peppermint#154]
Issue: When trying to change the email for the default admin@admin.com user, it does not apply. Trying to create a new user does not work

How to replicate:
1) Spin up a docker instance (my compose is below)
2) log in with default creds
3) Click view profile on admin user
4) attempt to change password
OR
3) click users 
4) attempt to create new user 

OS: Debian 11 (latest updates)
Docker version: 24.0.2

Compose: 

>     peppermint-db:
      container_name: peppermint-db
      image: postgres:latest
      restart: always
      volumes:
        - /containerstorage/peppermint/db:/data/db
      environment: 
        POSTGRES_USER: peppermint
        POSTGRES_PASSWORD: 1234
        POSTGRES_DB: peppermint
    peppermint-client:
      container_name: peppermint-client
      image: pepperlabs/peppermint:latest
      ports:
        - 8787:8787
      restart: always
      depends_on:
        - peppermint-db
      environment:
        PORT: 8787
        DB_USERNAME: peppermint
        DB_PASSWORD: 1234
        DB_HOST: 'peppermint-db'
        BASE_URL: "http://xx.xx.xx.xx:8787"

peppermint-client logs:

> 
Actions

      

No pending migrations to apply.

Done in 5.40s.

yarn run v1.22.19

$ prisma generate

Environment variables loaded from .env

Prisma schema loaded from prisma/schema.prisma

✔ Generated Prisma Client (3.7.0 | library) to ./node_modules/@prisma/client in 720ms

You can now start using Prisma Client in your code. Reference: https://pris.ly/d/client

```

import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

```

warn Versions of prisma@3.14.0 and @prisma/client@3.7.0 don't match.

This might lead to unexpected behavior.

Please make sure they have the same version.

┌─────────────────────────────────────────────────────────┐

│  Update available 3.14.0 -> 4.16.2                      │

│                                                         │

│  This is a major update - please follow the guide at    │

│  https://pris.ly/d/major-version-upgrade                │

│                                                         │

│  Run the following to update                            │

│    yarn add --dev prisma@latest                         │

│    yarn add @prisma/client@latest                       │

└─────────────────────────────────────────────────────────┘

Done in 13.66s.

yarn run v1.22.19

$ prisma db seed

Environment variables loaded from .env

Running seed command `node prisma/seed.js` ...

{

  admin: {

    id: 1,

    createdAt: 2023-07-05T19:45:33.474Z,

    updatedAt: 2023-07-05T19:45:33.474Z,

    name: 'admin',

    password: '$2b$10$BFmibvOW7FtY0soAAwujoO9y2tIyB7WEJ2HNq9O7zh9aeejMvRsKu',

    email: 'admin@admin.com',

    isAdmin: true

  },

  internal: {

    id: 1,

    createdAt: 2023-07-05T19:45:33.483Z,

    updatedAt: 2023-07-05T19:45:33.483Z,

    name: 'internal',

    email: 'internal@admin.com',

    contactName: 'admin',

    number: '123456789',

    notes: null

  }

}

🌱  The seed command has been executed.

Done in 3.47s.

yarn run v1.22.19


$ next start

ready - started server on 0.0.0.0:8787, url: http://localhost:8787

info  - Loaded env from /app/.env

warn  - SWC minify beta enabled. https://nextjs.org/docs/messages/swc-minify-enabled

6d5f296ac5149fe0f6d373eb8c253ee7abea68bf2f78f41aef686bba7d2e9236

{

  user: { name: 'admin', email: 'admin@admin.com', isAdmin: true, id: 1 },

  expires: '2023-08-04T19:48:24.980Z',

  id: 1

}

**Comment by jamess60** [comment]
Apologies for the formatting.... Quote and code both dont seem to format properly. Happy to paste bin it if required

**Comment by jamess60** [comment]
Edit: Trying to make a new client also does not work.

**Comment by jamess60** [comment]
More info

This is the output of the postgres container:

server stopped

PostgreSQL init process complete; ready for start up.

2023-07-05 19:58:39.943 UTC [1] LOG:  starting PostgreSQL 15.3 (Debian 15.3-1.pgdg120+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit

2023-07-05 19:58:39.944 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432

2023-07-05 19:58:39.944 UTC [1] LOG:  listening on IPv6 address "::", port 5432

2023-07-05 19:58:39.947 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"

2023-07-05 19:58:39.959 UTC [64] LOG:  database system was shut down at 2023-07-05 19:58:39 UTC

2023-07-05 19:58:39.976 UTC [1] LOG:  database system is ready to accept connections


It looks like peppermint never even attempts to write to the db?
/containerstorage/peppermint/db (my volume path) is also empty

**Comment by ChristianNik** [comment]
I have the same Problem.

Docker version: `20.10.21, build 20.10.21-0ubuntu1~22.04.3`

My config:
```yaml
version: "3.1"

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    volumes:
      - ./db:/data/db
    environment: 
      POSTGRES_USER: peppermint
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: peppermint

  client:
    container_name: peppermint
    image: pepperlabs/peppermint:latest
    ports:
      - 5000:5000
    restart: on-failure
    depends_on:
      - postgres
    environment:
      PORT: 5000
      DB_USERNAME: peppermint
      DB_PASSWORD: 1234
      DB_HOST: 'postgres'
      BASE_URL: "http://localhost:5000"
```
