### ISSUE TITLE
Unable to log into Peppermint

### ISSUE THREAD

**Issue by Zelatrix** [Peppermint-Lab/peppermint#187]
I've downloaded the newly-released ARM build and set it up in a Docker container. The output of `docker ps` says that both the Postgres and Peppermint containers are running, but when I go to the IP of the server that I set as the `BASE_URL`, it brings up a webpage with a JSON object on it like this

![image](https://github.com/Peppermint-Lab/peppermint/assets/39635013/6967bbf5-8555-4ff2-a6a0-c634585d32ac)

I don't know what it is that I am doing wrong. Any help is appreciated.

**Comment by potts99** [comment]
Hiya, with the new release there has been some updates to docker. Using the below and accessing via port 3000 should do the trick for you 

,,,
version: "3.1"

services:
  peppermint_postgres:
    container_name: peppermint_postgres
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: peppermint
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: peppermint

  peppermint:
    container_name: peppermint
    image: pepperlabs/peppermint:latest
    ports:
      - 3000:3000
      - 5003:5003
    restart: always
    depends_on:
      - peppermint_postgres
    healthcheck:
      test: ["CMD", "sh", "-c", "wget --spider $$BASE_URL"]
      interval: 30s
      timeout: 10s
      retries: 3
    environment:
      DB_USERNAME: "peppermint"
      DB_PASSWORD: "1234"
      DB_HOST: "peppermint_postgres"
      SECRET: 'peppermint4life'
      API_URL: "http://192.168.0.204:5003"

volumes:
pgdata:
,,,

**Comment by desrod** [comment]
@potts99 Exactly the same issue using your YAML above: 

Visiting http://1.2.3.4:5003 results in `{"healthy":true}` but no login UI. Hitting port 3003 is a dead end, nothing responds on that port.

**Comment by desrod** [comment]
I already have a container running on 3000, so I changed it to 3003, still doesn't work. Nothing listening on that port.

**Comment by desrod** [comment]
I stopped the container running on 3000, redeployed peppermint on port 3000, and it still behaves the same way. It never fully comes up and never starts anything on that port. 

```
> client@1.0.0 docker
> next build && next start
   Linting and checking validity of types ...
   Creating an optimized production build ...
Failed to compile.
./components/TipTapEditor/index.js
Module not found: Can't resolve 'classnames'
https://nextjs.org/docs/messages/module-not-found
Import trace for requested module:
./pages/tickets/new/[id]/index.js
./pages/_app.tsx
Module not found: Can't resolve 'antd/dist/antd.css'
https://nextjs.org/docs/messages/module-not-found
> Build failed because of webpack errors
2023-11-28T00:46:51: PM2 log: App [client:0] exited with code [1] via signal [SIGINT]
2023-11-28T00:46:51: PM2 log: App [client:0] starting in -fork mode-
2023-11-28T00:46:51: PM2 log: App [client:0] online
> client@1.0.0 docker
> next build && next start
   Linting and checking validity of types ...
   Creating an optimized production build ...
```

**Comment by potts99** [comment]
ah i see my bad, try this @desrod 

updating your port section of peppermint to 3003 on the outside, but still mapping to 3000 on the inside

```
 peppermint:
    container_name: peppermint
    image: pepperlabs/peppermint:latest
    ports:
      - 3003:3000
      - 5003:5003
    restart: always
    depends_on:
      - peppermint_postgres
    healthcheck:
      test: ["CMD", "sh", "-c", "wget --spider $$BASE_URL"]
      interval: 30s
      timeout: 10s
      retries: 3
    environment:
      DB_USERNAME: "peppermint"
      DB_PASSWORD: "1234"
      DB_HOST: "peppermint_postgres"
      SECRET: 'peppermint4life'
      API_URL: "http://server-ip:5003"
```
