### ISSUE TITLE
Race condition?

### ISSUE THREAD

**Issue by evansharp** [Peppermint-Lab/peppermint#196]
Thanks for the the quick help sorting out my ports @potts99! I use 3000 for another app, so a quick remap and proxy update I was in business.

As soon as I got the login page though, the whole server ground to a halt and hung though. After having to reboot the instance in Open Stack, I brought Pep up again and checked `htop` right away; I've attached the output. Nothing else on the server is using node, so 99.8% of that load, most of the memory, and all of those node build threads is Peppermint.

<img width="1115" alt="Screenshot 2023-11-28 at 3 54 23 PM" src="https://github.com/Peppermint-Lab/peppermint/assets/1461350/108c9bb1-7452-4b48-a88f-3fc868244a3c">

Any ideas? Memory and load just creep upwards every reboot even if I don't access the frontend.

**Comment by evansharp** [comment]
if the client console is any use, I managed to grab this in Chrome right after submitting admin login details. Page remains unresponsive, but these errors popped before the instance crashed completely.
<img width="1373" alt="Screenshot 2023-11-28 at 4 03 28 PM" src="https://github.com/Peppermint-Lab/peppermint/assets/1461350/b230f6fa-4c10-442d-b517-2f95409bd1e4">

**Comment by evansharp** [comment]
Hang on, I just noticed that the API port isn't being proxied. that might be it.

**Comment by evansharp** [comment]
5003 proxy is in place, but same error. I notice the unroutable URI contains `localhost`. Where does the app draw the BASE_URI from? Can I specify it explicitly in the ENV so that my browser isn't stuck trying to connect to my client machine's localhost?

**Comment by potts99** [comment]
That might be causing some issues -> first couple minutes are a little cpu intensive as it needs to do some building of the client first

**Comment by evansharp** [comment]
Ok, so I'll spec the instance a little higher. What about the URI spec in compose?

**Comment by potts99** [comment]
Its a one and done thing so you shouldnt need to after initial build it just can take around 4/5 mins. 

You dont need a base url anymore, updating docs as we speak 

```
version: "3.1"

services:
  peppermint_postgres:
    container_name: peppermint_postgres
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: peppermint
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: peppermint

  peppermint:
    container_name: peppermint
    image: pepperlabs/peppermint:latest
    ports:
      - 3000:3000
      - 5003:5003
    restart: always
    depends_on:
      - peppermint_postgres
    healthcheck:
      test: ["CMD", "sh", "-c", "wget --spider $$BASE_URL"]
      interval: 30s
      timeout: 10s
      retries: 3
    environment:
      DB_USERNAME: "peppermint"
      DB_PASSWORD: "1234"
      DB_HOST: "peppermint_postgres"
      SECRET: 'peppermint4life'
      API_URL: "http://server-ip:5003"

volumes:
 pgdata:
```

Update API_URL to the proxy for 5003


example
```
API_URL: "http://api.google.com"
```

This should proxy to 5003 and work

**Comment by evansharp** [comment]
The node processes are still overrunning my up=-scaled instances hours after a restart. What can I provide to help you with this?

**Comment by potts99** [comment]
Docker logs for peppermint container @evansharp

**Comment by potts99** [comment]
Unfortunately it's just to the web framework nextJs pre compiles environment variables at build time, so the ideal scenario would be pre complied build on my side ... looking to find a way around this but it would mean probably a full rewrite

**Comment by evansharp** [comment]
I opened this issue to ask about the resources of static building, but I'm jammed up on the proxy too. I've done it a thousand times and cannot see what the issue is.

In the Apache site config
```
ProxyPreserveHost On
  ProxyRequests off

  TimeOut 2400
  ProxyTimeout 2400
  ProxyBadHeader Ignore

  # Frontend (dodge 3000 for conflict)
  ProxyPass / http://localhost:3003/
  ProxyPassReverse / http://localhost:3003/

  # API/backend
  ProxyPass / http://localhost:5003/
  ProxyPassReverse / http://localhost:5003/

  <Proxy *>
        Require all granted
  </Proxy>
```
In the Docker compose
```
version: "3.1"

services:
  peppermint_postgres:
    container_name: peppermint_postgres
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: peppermint
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: peppermint

  peppermint:
    container_name: peppermint
    image: pepperlabs/peppermint:latest
    ports:
      - 3003:3000
      - 5003:5003
    restart: always
    depends_on:
      - peppermint_postgres
    healthcheck:
      test: ["CMD", "sh", "-c", "wget --spider $$BASE_URL"]
      interval: 30s
      timeout: 10s
      retries: 3
    environment:
      DB_USERNAME: "peppermint"
      DB_PASSWORD: "1234"
      DB_HOST: "peppermint_postgres"
      SECRET: 'peppermint4life'
      API_URL: "https://<subdomain.domain.com>"

volumes:
 pgdata:
```

**Comment by potts99** [comment]
If you try hitting the api in something like postman or in the browser do you see a healthy: true?

**Comment by evansharp** [comment]
yes and yes. Login redirect works from the root and page loads. The request triggered by a login button click shows in the apache access log as a 404, but the path is well-formed:
`========== - - [29/Nov/2023:11:20:40 -0800] "POST /api/v1/auth/login HTTP/1.1" 404 7630 "https://subdomain.domain.com/auth/login" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Ge
cko) Chrome/119.0.0.0 Safari/537.36"`

**Comment by potts99** [comment]
Try adding port 5003 to the end of your current API_URL and re-composing, I think that may be the issue

**Comment by evansharp** [comment]
It times out. If the API_URL has :5003 explicit, then the client request hits the proxy on port 5003, which it isn't configured for. It's listening on 443 for that request (alongside frontend requests) and sending it to 5003 in the container.

Does the frontend automatically do API requests on 5003? If so I'll need a separate virtual host to proxy it.

**Comment by evansharp** [comment]
This is weird. I went ahead and created a new virtual host to listen on 5003, while leaving the :5003 explicit on the API_URL. I'm not even seeing the requests in the apache logs now. Browser console has `fetching user profile` and then request timeouts. So even when hand-railing the ports it's not responding. And yes, the port is open in the firewall.

**Comment by potts99** [comment]
The front end only cares about the url -> if it requested api.peppermint.com behind a proxy it would still hit 192.168.0.1:5003

**Comment by potts99** [comment]
if you can hit the api in the browser, you should always be able to hit the api with the front end via API_UrL

If you try ```https://<subdomain.domain.com:5003``` in your browser does that return the api?

**Comment by evansharp** [comment]
Nope. timeout.

> The front end only cares about the url 
I guess what I'm asking is, when the frontend page emits a request, is it appending the :5003? or targeting the exact string of API_URL (so https:// --> :443, http:// --> 80, :5003 --> :5003). 

- Are all backend requests routed through /api/? I think I might have a matching issue.

**Comment by potts99** [comment]
the exact string, the client is then hardcoded from /api/

**Comment by potts99** [comment]
if this ```https://<subdomain.domain.com:5003``` is timing out then it means your subdomain cant see the api

**Comment by potts99** [comment]
Manged to recreate the issue -> api also needs a subdomain -> api.example.com and needs to be a https resource to work

**Comment by evansharp** [comment]
I came to the same conclusion last night, but with a different solution. I realized that because apache matches the first rule, the root of the URI `/` would capture every request and send it to `:3003` regardless of anything else. 

My (untested) idea is that if I map the next segment of api requests, provided that is consistent (e.g. `/api/`), and place it ahead of the root mapping in the existing virtual host, then the it will match first in those cases and can route those requests to `:5003`. This makes for a cleaner DNS setup than a whole other subdomain; although I see the utility of being able to separate out the API_URL from the BASE_URL in the compose.

As an aside, I see some inconsistencies in the reverse proxy doc you shared:
- The healthcheck in the provided compose looks at the API_URL var rather than the BASE_URL as in other composes?
- Where is the BASE_URL specificied? Is the frontend just collecting that from how the initial request came in? Could that not be accidentally spoofed if some other URL is routed to `:3000`?
- The additional note at the bottom mentions api requests needing to be SSL, but the nginx config for the proxy domain is listening on `:80`

Once I get this working, would you be open to a PR for that page to capture all this work we've done?

**Comment by potts99** [comment]
hello @evansharp just finished working on a way to simplify getting set up its on a test branch with a host of other things such as a new ui.

You only need ONE subdomain now for port 3000 you dont have to worry about any api urls anymore!

ignore base_urls and api_urls

```
version: "3.1"

services:
  peppermint_postgres:
    container_name: peppermint_postgres
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: peppermint
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: peppermint

  peppermint:
    container_name: peppermint
    image: pepperlabs/peppermint:test
    ports:
      - 3000:3000
      - 5003:5003
    restart: always
    depends_on:
      - peppermint_postgres
    environment:
      DB_USERNAME: "peppermint"
      DB_PASSWORD: "1234"
      DB_HOST: "peppermint_postgres"
      SECRET: 'peppermint4life'

volumes:
 pgdata:
 ```

Hopefully youre still in the mood to set this up :)
