### ISSUE TITLE
Unable to Login

### ISSUE THREAD

**Issue by Nelztacy** [Peppermint-Lab/peppermint#203]
![Peppermint-Ticket](https://github.com/Peppermint-Lab/peppermint/assets/105312355/f7b19e69-026a-430f-ba72-9f59ba43eea6)
I deployed Peppermint_Lab on Docker, it ran successfully but won't accept default login details on start page

**Comment by potts99** [comment]
Hey mate,

Could you provide an example of your docker compose and an example of the address you're accessing from

**Comment by azarielI** [comment]
I'm having this same problem. I just installed this on docker and I can't sign in. The login page only gives me a field to input the email address. I type in admin@admin.com and hit sign in, and nothing happens. The button doesn't do anything.

**Comment by potts99** [comment]
sorted via discord 

use latest compose as linode arent replying to me

```
version: "3.1"

services:
  peppermint_postgres:
    container_name: peppermint_postgres
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: peppermint
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: peppermint

  peppermint:
    container_name: peppermint
    image: pepperlabs/peppermint:latest
    ports:
      - 3000:3000
      - 5003:5003
    restart: always
    depends_on:
      - peppermint_postgres
    healthcheck:
      test: ["CMD", "sh", "-c", "wget --spider $$API_URL"]
      interval: 30s
      timeout: 10s
      retries: 3
    environment:
      DB_USERNAME: "peppermint"
      DB_PASSWORD: "1234"
      DB_HOST: "peppermint_postgres"
      SECRET: 'peppermint4life'
      API_URL: "http://server-ip:5003"

volumes:
 pgdata:
```

**Comment by potts99** [comment]
update your api_url to your ip that you are accessing the front end via

**Comment by azarielI** [comment]
@potts99 I'm not using linode. I'm using a hetzner vps and that is the docker file I copied.

**Comment by potts99** [comment]
My bad @azarielI are you using a subdomain by any chance?

**Comment by azarielI** [comment]
> My bad @azarielI are you using a subdomain by any chance?

Yes, I was trying to use this on a site with a subdomain.

**Comment by potts99** [comment]
cool ive simplified this process just yesterday, its available on the test branch 

```
version: "3.1"

services:
  peppermint_postgres:
    container_name: peppermint_postgres
    image: postgres:latest
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: peppermint
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: peppermint

  peppermint:
    container_name: peppermint
    image: pepperlabs/peppermint:test
    ports:
      - 3000:3000
    restart: always
    depends_on:
      - peppermint_postgres
    environment:
      DB_USERNAME: "peppermint"
      DB_PASSWORD: "1234"
      DB_HOST: "peppermint_postgres"
      SECRET: 'peppermint4life'

volumes:
 pgdata:
 ```
 
 port 3000 to redirect to your proxy
