### ISSUE TITLE
Docs for connecting to external database server during setup/installation 

### ISSUE THREAD

**Issue by AlisterBaroi** [Peppermint-Lab/peppermint#359]
What if, let's say, I want to deploy peppermint, but without setting up the database from the docker compose file.

**I want to just assign the environment variables of the database to the peppermint service, so that I can connect to a separate database hosted at a cloud provider (let's say).**

Benefits:
- Peppermint can be setup using just a Dockerfile,
- Option to not manually setup database for the peppermint, just connect to an already-existing DB hosted somewhere instead,

The docker compose with the single service would look like this (can also be converted to a single Dockerfile):
```
version: "3.1"

services:
  peppermint:
    container_name: peppermint
    image: pepperlabs/peppermint:latest
    ports:
      - 3000:3000
      - 5003:5003
    restart: always
    healthcheck:
      test: ["CMD", "sh", "-c", "wget --spider $$API_URL"]
      interval: 30s
      timeout: 10s
      retries: 3
    environment:
      DB_USERNAME: "name-of-empty-external-DB"
      DB_PASSWORD: "pass-of-empty-external-DB"
      DB_HOST: "ip-of-empty-external-DB"
      SECRET: 'peppermint4life'

volumes:
 pgdata:
```
