### ISSUE TITLE
Problem with SMTP configuration

### ISSUE THREAD

**Issue by brunobeeee** [Peppermint-Lab/peppermint#424]
Hello,

I'm trying to get E-Mail sending to work. I go to **admin panel -> smtp e-mail** and fill out the form. When I click **submit** the site gets blank with a "loading..." notice and after a few seconds I just restart at the beginning of the SMTP form:
<img width="950" alt="Bildschirmfoto 2024-11-26 um 17 10 21" src="https://github.com/user-attachments/assets/291ff18f-5d15-45a9-b0bb-393fa1a282e2">

In the logs I can see two errors which I don't quite understand:
```
peppermint           | Failed to proxy http://localhost:5003/api/v1/config/email Error: socket hang up
peppermint           |     at Socket.socketCloseListener (node:_http_client:479:27)
peppermint           |     at Socket.emit (node:events:530:35)
peppermint           |     at TCP.<anonymous> (node:net:343:12) {
peppermint           |   code: 'ECONNRESET'
peppermint           | }
peppermint           | Error: socket hang up
peppermint           |     at Socket.socketCloseListener (node:_http_client:479:27)
peppermint           |     at Socket.emit (node:events:530:35)
peppermint           |     at TCP.<anonymous> (node:net:343:12) {
peppermint           |   code: 'ECONNRESET'
peppermint           | }
peppermint           | No new messages
peppermint           | Email fetch completed
peppermint           | Connection ended
peppermint           | No new messages
peppermint           | Email fetch completed
peppermint           | Connection ended
peppermint           | No new messages
peppermint           | Email fetch completed
peppermint           | Connection ended
peppermint           | No new messages
peppermint           | Email fetch completed
peppermint           | Connection ended
peppermint           | ERROR Error: Connection timeout
peppermint           |     at SMTPConnection._formatError (/apps/api/node_modules/nodemailer/lib/smtp-connection/index.js:807:19)
peppermint           |     at SMTPConnection._onError (/apps/api/node_modules/nodemailer/lib/smtp-connection/index.js:793:20)
peppermint           |     at Timeout.<anonymous> (/apps/api/node_modules/nodemailer/lib/smtp-connection/index.js:237:22)
peppermint           |     at listOnTimeout (node:internal/timers:594:17)
peppermint           |     at process.processTimers (node:internal/timers:529:7) {
peppermint           |   code: 'ETIMEDOUT',
peppermint           |   command: 'CONN'
peppermint           | }
```

<details><summary>My setup</summary>

`docker-compose.yml`:
```yaml
services:
  peppermint_postgres:
    container_name: peppermint_postgres
    image: postgres:latest
    networks:
      - default
    restart: unless-stopped
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: peppermint
      POSTGRES_PASSWORD: *****
      POSTGRES_DB: peppermint

  peppermint:
    container_name: peppermint
    image: pepperlabs/peppermint:latest
    # ports:
    #   - 3000:3000
    #   - 5003:5003
    networks:
      - default
      - caddy_default
    restart: unless-stopped
    depends_on:
      - peppermint_postgres
    environment:
      DB_USERNAME: "peppermint"
      DB_PASSWORD: "*****"
      DB_HOST: "peppermint_postgres"
      SECRET: '*****'

networks:
  default:
  caddy_default:
    external: true
```

As you can see my reverse proxy is caddy with this configuration:
```
peppermint.example.tld {
    reverse_proxy http://peppermint:3000
}

peppermintapi.example.tld {
    reverse_proxy http://peppermint:5003
}
```

</details> 

I hope you can help me. Thank you for your amazing work!
