### ISSUE TITLE
Reverse proxy base url

### ISSUE THREAD

**Issue by Brantlab** [Peppermint-Lab/peppermint#72]
Allow us to set the port in the base url. I have mine sitting behind reverse proxy and I end up at baseurl:5020 when the reverse proxy handles the the 80>5020 transversal.

**Comment by potts99** [comment]
Yeah another users has also raised a similar issue, I think its how i've got the baseurl set up, looking into it now should have an answer shortly :)

**Comment by potts99** [comment]
Hello 

Could you test this for me 
```
version: "3.1"

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    volumes:
      - ./peppermint/db:/data/db
    environment: 
      POSTGRES_USER: peppermint
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: peppermint

  client:
    container_name: peppermint
    image: pepperlabs/peppermint:test
    ports:
      - 3001:3001
    restart: on-failure
    depends_on:
      - postgres
    environment:
      PORT: 3001
      DB_USERNAME: "peppermint"
      DB_PASSWORD: "1234"
      DB_HOST: "postgres"
      BASE_URL: "http://localhost:3001"
```

i'm guessing you would just need to change the base url to your reserves proxy url. 
Currently setting up a linode box to test this myself

**Comment by potts99** [comment]
I have this working for myself with this docker compose file -> will update main after i get from the gym

```
version: "3.1"

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    volumes:
      - ./peppermint/db:/data/db
    environment:
      POSTGRES_USER: peppermint
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: peppermint

  client:
    container_name: peppermint
    image: pepperlabs/peppermint:test
    ports:
      - 3001:3001
    restart: on-failure
    depends_on:
      - postgres
    expose:
      - 3001
    environment:
      PORT: 3001
      DB_USERNAME: "peppermint"
      DB_PASSWORD: "1234"
      DB_HOST: "postgres"
      BASE_URL: "https://test.peppermint.sh/"
```
