### ISSUE TITLE
TypeError after fresh install

### ISSUE THREAD

**Issue by kubeworkz** [Peppermint-Lab/peppermint#99]
I get the following error after a new install:

```error - TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["Location"]```

**Comment by potts99** [comment]
can you share your compose file

**Comment by kubeworkz** [comment]
```
version: "3.1"

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    volumes:
      - ./peppermint/db:/data/db
    environment: 
      POSTGRES_USER: peppermint
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: peppermint

  client:
    container_name: peppermint
    image: pepperlabs/peppermint:latest
    ports:
      - 5001:5001
    restart: on-failure
    depends_on:
      - postgres
    environment:
      PORT: 5001
      DB_USERNAME: "peppermint"
      DB_PASSWORD: "1234"
      DB_HOST: "postgres"
      BASE_URL: "http://localhost:5001"
```
